services:
  karaoke-app:
    build: .
    restart: unless-stopped
    environment:
      - PROXY_SERVER=${PROXY_SERVER}
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - DOMAIN=${DOMAIN:-localhost}
    # Port 8000 is internal only - accessed via Caddy reverse proxy
    # Uncomment the ports section below for development/debugging
    # ports:
    #   - "8000:8000"
    # Health check for the karaoke app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN:-localhost}

# Optional: Create a custom network for better isolation
networks:
  default:
    name: karaoke-network

volumes:
  caddy_data:
  caddy_config:
